# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 274e536dc4fc80775342fa5e7960a321f6884fec144eb20b91a2456a3c5f25b1151fb6b325bb8f2f74a3ccbe56eae0f90a161ea5a47812b7b5283144824fe399

test:
  secret_key_base: f8df1671b65a80e50b393063db45bc9c53b4b0853263ba6db43ab2f003c961795ff277942e34a34f2f88a1e00a96915211b11deaa3af1b6c337bb19628afea3d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
